Insert into strength_unit (unit_name) values('mg');
Insert into strength_unit (unit_name) values('g');
Insert into strength_unit (unit_name) values('ml');
Insert into strength_unit (unit_name) values('micrograms');
Insert into strength_unit (unit_name) values('tablets');
Insert into strength_unit (unit_name) values('capsule');

insert into dose_frequency (time_unit,noof_doses) values('Daily',1);
insert into dose_frequency (time_unit,noof_doses) values('Daily',2);
insert into dose_frequency (time_unit,noof_doses) values('Daily',3);
insert into dose_frequency (time_unit,noof_doses) values('Daily',4);
insert into dose_frequency (time_unit,noof_doses) values('Daily',6);
insert into dose_frequency (time_unit,noof_doses) values('Daily',8);
insert into dose_frequency (time_unit,noof_doses) values('Daily',12);
insert into dose_frequency (time_unit,noof_doses) values('Daily',24);
insert into dose_frequency (time_unit,noof_doses) values('Weekly',1);
insert into dose_frequency (time_unit,noof_doses) values('Weekly',2);
insert into dose_frequency (time_unit,noof_doses) values('Weekly',3);
insert into dose_frequency (time_unit,noof_doses) values('Every other day',1);
insert into dose_frequency (time_unit,noof_doses) values('Monthly',1);
insert into dose_frequency (time_unit,noof_doses) values('When Needed',1);
insert into dose_frequency (time_unit,noof_doses) values('Morning',1);
insert into dose_frequency (time_unit,noof_doses) values('Night',1);
insert into dose_frequency (time_unit,noof_doses) values('Noon',1);
insert into dose_frequency (time_unit,noof_doses) values('Evening',1);
insert into dose_frequency (time_unit,noof_doses) values('Bed Time',1);

Insert into base_drug (base_drug_name) values('Amoxicillin');
Insert into base_drug (base_drug_name) values('Hexalen');
Insert into base_drug (base_drug_name) values('Paracetamol');
Insert into base_drug (base_drug_name) values('Methodone');
Insert into base_drug (base_drug_name) values('Folic Acid');
Insert into base_drug (base_drug_name) values('Norco');
Insert into base_drug (base_drug_name) values('Ibuprofen');
Insert into base_drug (base_drug_name) values('Volteran');
Insert into base_drug (base_drug_name) values('Penicillamine');
Insert into base_drug (base_drug_name) values('Vitamin D');

Insert into drug (brand_name,base_drug_id) values('Amoxil', 1);
Insert into drug (brand_name,base_drug_id) values('Amoxicot', 1);
Insert into drug (brand_name,base_drug_id) values('Amoxicot', 1);
Insert into drug (brand_name,base_drug_id) values('Hexalen', 2);
Insert into drug (brand_name,base_drug_id) values('Tylenol', 3);
Insert into drug (brand_name,base_drug_id) values('Panadol', 3);
Insert into drug (brand_name,base_drug_id) values('Calpol', 3);
Insert into drug (brand_name,base_drug_id) values('Methadose', 4);
Insert into drug (brand_name,base_drug_id) values('Dolophine', 4);
Insert into drug (brand_name,base_drug_id) values(' Methadone Diskets', 4);
Insert into drug (brand_name,base_drug_id) values(' Folvite', 5);
Insert into drug (brand_name,base_drug_id) values('Folacin-800', 5);
Insert into drug (brand_name,base_drug_id) values('FaLessa, FA-8', 5);
Insert into drug (brand_name,base_drug_id) values('Vicodin', 6);
Insert into drug (brand_name,base_drug_id) values('Hycet', 6);
Insert into drug (brand_name,base_drug_id) values('Lorcet', 6);
Insert into drug (brand_name,base_drug_id) values('Medipren', 7);
Insert into drug (brand_name,base_drug_id) values('Motrin', 7);
Insert into drug (brand_name,base_drug_id) values('Nuprin', 7);
Insert into drug (brand_name,base_drug_id) values('Voltaren', 8);
Insert into drug (brand_name,base_drug_id) values('Cataflam', 8);
Insert into drug (brand_name,base_drug_id) values('Zipsor', 8);
Insert into drug (brand_name,base_drug_id) values('Cuprimine', 9);
Insert into drug (brand_name,base_drug_id) values('Depen', 9);
Insert into drug (brand_name,base_drug_id) values('Depen Titratabs', 9);
Insert into drug (brand_name,base_drug_id) values('Vita D', 10);

Insert into duration_unit (duration_unit) values ('Days');
Insert into duration_unit (duration_unit) values ('Hours');
Insert into duration_unit (duration_unit) values ('Weeks');
Insert into duration_unit (duration_unit) values ('Months');



Insert into strength (unit_id,strength_amount) values(1,100);
Insert into strength (unit_id,strength_amount) values(1,200);
Insert into strength (unit_id,strength_amount) values(1,300);
Insert into strength (unit_id,strength_amount) values(1,400);
Insert into strength (unit_id,strength_amount) values(1,500);
Insert into strength (unit_id,strength_amount) values(2,2);
Insert into strength (unit_id,strength_amount) values(2,5);
Insert into strength (unit_id,strength_amount) values(2,10);
Insert into strength (unit_id,strength_amount) values(2,3);
Insert into strength (unit_id,strength_amount) values(2,12);
Insert into strength (unit_id,strength_amount) values(3,100);
Insert into strength (unit_id,strength_amount) values(3,200);
Insert into strength (unit_id,strength_amount) values(3,300);
Insert into strength (unit_id,strength_amount) values(3,400);
Insert into strength (unit_id,strength_amount) values(3,500);
Insert into strength (unit_id,strength_amount) values(3,600);
Insert into strength (unit_id,strength_amount) values(3,700);
Insert into strength (unit_id,strength_amount) values(3,800);
Insert into strength (unit_id,strength_amount) values(3,900);
Insert into strength (unit_id,strength_amount) values(3,1000);
Insert into strength (unit_id,strength_amount) values(4,500);
Insert into strength (unit_id,strength_amount) values(4,200);
Insert into strength (unit_id,strength_amount) values(4,400);
Insert into strength (unit_id,strength_amount) values(4,1000);
Insert into strength (unit_id,strength_amount) values(4,300);
Insert into strength (unit_id,strength_amount) values(5,0);
Insert into strength (unit_id,strength_amount) values(6,0);


insert into product_type (itemtype) values('Medicine');
insert into product_type (itemtype) values('Services');
insert into product_type (itemtype) values('Other');

Insert into unit_of_measure (unit_of_measure) values('mg');
Insert into unit_of_measure (unit_of_measure) values('g');
Insert into unit_of_measure (unit_of_measure) values('ml');
Insert into unit_of_measure (unit_of_measure) values('micrograms');
Insert into unit_of_measure (unit_of_measure) values('Packets');
Insert into unit_of_measure (unit_of_measure) values('Boxes');

insert into dose_frequency (time_unit,noof_doses) values('Daily',1);
insert into dose_frequency (time_unit,noof_doses) values('Daily',2);
insert into dose_frequency (time_unit,noof_doses) values('Daily',3);
insert into dose_frequency (time_unit,noof_doses) values('Daily',4);
insert into dose_frequency (time_unit,noof_doses) values('When needed',0);
insert into dose_frequency (time_unit,noof_doses) values('Stat and repeat in 1 week',0);
insert into dose_frequency (time_unit,noof_doses) values('2 hourly',12);
insert into dose_frequency (time_unit,noof_doses) values('4 hourly',6);
insert into dose_frequency (time_unit,noof_doses) values('5 hourly',5);
insert into dose_frequency (time_unit,noof_doses) values('6 hourly',4);
insert into dose_frequency (time_unit,noof_doses) values('8 hourly',3);
insert into dose_frequency (time_unit,noof_doses) values('12 hourly',2);
insert into dose_frequency (time_unit,noof_doses) values('Every other day',1);
insert into dose_frequency (time_unit,noof_doses) values('Monthly',1);
insert into dose_frequency (time_unit,noof_doses) values('Morning',1);
insert into dose_frequency (time_unit,noof_doses) values('Night',1);
insert into dose_frequency (time_unit,noof_doses) values('Noon',1);
insert into dose_frequency (time_unit,noof_doses) values('Evening',1);
insert into dose_frequency (time_unit,noof_doses) values('At Bed Time',1);
insert into dose_frequency (time_unit,noof_doses) values('1 time a Week',1);
